config/routes.rb
Rails.application.routes.draw do
  resources :burgers do
    post 'apply_promo', on: :member
  end
  resources :promotions
  # Root route
  root "burgers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/burger.rb
class Burger < ApplicationRecord
  has_one :promotion
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :burger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  before_action :set_burger, only: %i[ show edit update destroy ]

  # GET /burgers or /burgers.json
  def index
    @burgers = Burger.all
  end

  # GET /burgers/1 or /burgers/1.json
  def show
  end

  # GET /burgers/new
  def new
    @burger = Burger.new
  end

  # GET /burgers/1/edit
  def edit
  end

  # POST /burgers or /burgers.json
  def create
    @burger = Burger.new(burger_params)

    respond_to do |format|
      if @burger.save
        format.html { redirect_to burger_url(@burger), notice: "Burger was successfully created." }
        format.json { render :show, status: :created, location: @burger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /burgers/1 or /burgers/1.json
  def update
    respond_to do |format|
      if @burger.update(burger_params)
        format.html { redirect_to burger_url(@burger), notice: "Burger was successfully updated." }
        format.json { render :show, status: :ok, location: @burger }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /burgers/1 or /burgers/1.json
  def destroy
    @burger.destroy!

    respond_to do |format|
      format.html { redirect_to burgers_url, notice: "Burger was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  def apply_promo
    @burger = Burger.find(params[:id])
    @promotion = Promotion.find_by(code: params[:promo_code], active: true)

    if @promotion
      @discounted_price = @burger.price - @promotion.discount
      flash[:notice] = "Kod promocyjny zastosowany! Nowa cena to #{@discounted_price}"
    else
      flash[:alert] = "Nieprawidłowy kod promocyjny"
    end

    render :show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_burger
      @burger = Burger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def burger_params
      params.require(:burger).permit(:name, :description, :price)
    end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :set_promotion, only: %i[ show edit update destroy ]

  # GET /promotions or /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1 or /promotions/1.json
  def show
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
  end

  # GET /promotions/1/edit
  def edit
  end

  # POST /promotions or /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to promotion_url(@promotion), notice: "Promotion was successfully created." }
        format.json { render :show, status: :created, location: @promotion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1 or /promotions/1.json
  def update
    respond_to do |format|
      if @promotion.update(promotion_params)
        format.html { redirect_to promotion_url(@promotion), notice: "Promotion was successfully updated." }
        format.json { render :show, status: :ok, location: @promotion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1 or /promotions/1.json
  def destroy
    @promotion.destroy!

    respond_to do |format|
      format.html { redirect_to promotions_url, notice: "Promotion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def promotion_params
      params.require(:promotion).permit(:code, :discount, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/burgers/_burger.html.erb
<div id="<%= dom_id burger %>">
  <p>
    <strong>Name:</strong>
    <%= burger.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= burger.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= burger.price %>
  </p>

</div>

app/views/burgers/_form.html.erb
<%= form_with(model: burger) do |form| %>
  <% if burger.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(burger.errors.count, "error") %> prohibited this burger from being saved:</h2>

      <ul>
        <% burger.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/burgers/edit.html.erb
<h1>Editing burger</h1>

<%= render "form", burger: @burger %>

<br>

<div>
  <%= link_to "Show this burger", @burger %> |
  <%= link_to "Back to burgers", burgers_path %>
</div>

app/views/burgers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Burgers</h1>

<div id="burgers">
  <% @burgers.each do |burger| %>
    <%= render burger %>
    <p>
      <%= link_to "Show this burger", burger %>
    </p>
  <% end %>
</div>

<%= link_to "New burger", new_burger_path %>

app/views/burgers/new.html.erb
<h1>New burger</h1>

<%= render "form", burger: @burger %>

<br>

<div>
  <%= link_to "Back to burgers", burgers_path %>
</div>

app/views/burgers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @burger %>




<%= form_with url: apply_promo_burger_path(@burger), method: :post, local: true do %>
  <div class="field">
    <%= label_tag :promo_code, "Kod promocyjny" %>
    <%= text_field_tag :promo_code %>
  </div>
  <div class="actions">
    <%= submit_tag "Zastosuj kod" %>
  </div>
<% end %>



<div>
  <%= link_to "Edit this burger", edit_burger_path(@burger) %> |
  <%= link_to "Back to burgers", burgers_path %>

  <%= button_to "Destroy this burger", @burger, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BurgerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/promotions/_form.html.erb
<%= form_with(model: promotion) do |form| %>
  <% if promotion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
        <% promotion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :discount, style: "display: block" %>
    <%= form.text_field :discount %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/promotions/_promotion.html.erb
<div id="<%= dom_id promotion %>">
  <p>
    <strong>Code:</strong>
    <%= promotion.code %>
  </p>

  <p>
    <strong>Discount:</strong>
    <%= promotion.discount %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= promotion.active %>
  </p>

</div>

app/views/promotions/edit.html.erb
<h1>Editing promotion</h1>

<%= render "form", promotion: @promotion %>

<br>

<div>
  <%= link_to "Show this promotion", @promotion %> |
  <%= link_to "Back to promotions", promotions_path %>
</div>

app/views/promotions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Promotions</h1>

<div id="promotions">
  <% @promotions.each do |promotion| %>
    <%= render promotion %>
    <p>
      <%= link_to "Show this promotion", promotion %>
    </p>
  <% end %>
</div>

<%= link_to "New promotion", new_promotion_path %>

app/views/promotions/new.html.erb
<h1>New promotion</h1>

<%= render "form", promotion: @promotion %>

<br>

<div>
  <%= link_to "Back to promotions", promotions_path %>
</div>

app/views/promotions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @promotion %>

<div>
  <%= link_to "Edit this promotion", edit_promotion_path(@promotion) %> |
  <%= link_to "Back to promotions", promotions_path %>

  <%= button_to "Destroy this promotion", @promotion, method: :delete %>
</div>